### ISSUE TITLE
Not compatible with Django 1.7

### ISSUE THREAD

**Issue by danpalmer** [lamby/django-auto-one-to-one#1]
`AutoOneToOneModel`, and by proxy, `PerUserData` are evaluated at model import time. They rely on `django.db.models.get_model`, which now proxies to `django.apps.apps.get_model`. The app registry however will not return results until the application setup has finished, and until all models are imported, creating a circular dependency.

I believe one possible fix would be to push lines [88-96](https://github.com/lamby/django-auto-one-to-one/blob/master/django_auto_one_to_one/models.py#L88-L96) down into the initialiser of `Parent`, ensuring that `get_model` is not called until a model object is instantiated.

**Comment by danpalmer** [comment]
We attempted to fix this by moving the code at those lines into `Base.__new__`, dynamically adding the one to one field to the parent class at model instantiation time. While this fixed the issue, it created more problems with other code that expected the fields to be there after class instantiation, specifically `cache_toolbox.cache_relation`.

The workaround we are using now is to require the passing of classes to `AutoOneToOneModel`, disallowing strings that require a lookup to get the model.

**Comment by lamby** [comment]
pu/get-user-model branch et. al

Clearly we need to use AppConfig but I'm not sure of the best way forward, especially re. backwards compat.

**Comment by petterreinholdtsen** [comment]
I get this backtrace when trying to use the library:

```
Traceback (most recent call last):
  File "./bitmynthandel-manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/lib/python3/dist-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pere/src/bitmynt/bm-website/trade/models.py", line 184, in <module>
    class UserProfile(django_auto_one_to_one.PerUserData('userprofile')):
  File "/usr/lib/python3/dist-packages/django_auto_one_to_one/models.py", line 155, in PerUserData
    return AutoOneToOneModel(get_user_model(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/contrib/auth/__init__.py", line 163, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "/usr/lib/python3/dist-packages/django/apps/registry.py", line 192, in get_model
    self.check_models_ready()
  File "/usr/lib/python3/dist-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```

This is using Django 1.10.7.  It seem to be the problem described here.

**Comment by petterreinholdtsen** [comment]
I started with this one, which gave the above error:

```
class Profile(PerUserData('userprofile')):
    uuid = models.UUIDField(unique=True,
                            default=uuid.uuid4,
                            editable=False)
```

I was able to get it working by rewriting it like this:

```
class UserProfile(AutoOneToOneModel(User, 'userprofile')):
    uuid = models.UUIDField(unique=True,
                            default=uuid.uuid4,
                            editable=False)
```

This avoid the problematic string lookup by using the `User` class directly.
