### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by petterreinholdtsen** [lamby/django-auto-one-to-one#5]
When building a Debian package, I get this backtrace during self test:

```
ERROR: django_auto_one_to_one (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: django_auto_one_to_one
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/pere/src/bitmynt/deb/django-auto-one-to-one/django_auto_one_to_one/__init__.py", line 1, in <module>
    from .models import AutoOneToOneModel, PerUserData
  File "/home/pere/src/bitmynt/deb/django-auto-one-to-one/django_auto_one_to_one/models.py", line 5, in <module>
    from django.contrib.auth.models import User
  File "/usr/lib/python3/dist-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/lib/python3/dist-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/lib/python3/dist-packages/django/contrib/auth/base_user.py", line 53, in AbstractBaseUser
    password = models.CharField(_('password'), max_length=128)
  File "/usr/lib/python3/dist-packages/django/db/models/fields/__init__.py", line 1043, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/fields/__init__.py", line 166, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 39, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

I can reproduce it by running `python3 setup.py test`.

**Comment by lamby** [comment]
This is for all Python versions, not just Python 3.x - retitling to match.
